### PR TITLE
fix default solver selection for CuSparseMatrix

### LINKED ISSUE #827: Default algs for CUSPARSE failing
Currently, the default algorithm choice is not really able to handle sparse cuda matrices. In short:

- `CuSparseMatrixCSC` -> defaults always to `GenericLU` which is not GPU compatible (scalar indexing)
- `CuSparseMatrixCSR`
  -  `CUDSS` not available -> defaults to Krylov which not GPU compatibe (scalar indexing). It gives a warning however
  -  `CUDSS` available + asym matrix -> works
  - `CUDSS` available + symmetric matrix -> Cholesky which is not GPU compatible (scalar indexing)

I am not sure what the right thing here is. Maybe just give a clearer error message? Or maybe convert to dense?

Code to play around with:

```julia
using LinearSolve
using SparseArrays
using CUDA
using CUDSS

b = Float64[1, 2, 3, 4]
b_gpu = adapt(CuArray, b)

A = Float64[1 1 0 0
            0 1 1 0
            0 0 3 1
            0 0 0 4]
A_sym = Float64[1 1 0 0
                1 0 0 2
                0 0 3 0
                0 2 0 0]

# asymetric matrix on GPU (dense)
A_gpu = adapt(CuArray, A)
prob_gpu = LinearProblem(A_gpu, b_gpu)
solve(prob_gpu) # works

# asymetric sparse matrix
A_gpu_sparse1 = CUDA.CUSPARSE.CuSparseMatrixCSR(sparse(A))
prob_gpu_sparse1 = LinearProblem(A_gpu_sparse1, b_gpu)
solve(prob_gpu_sparse1) # works

A_gpu_sparse2 = CUDA.CUSPARSE.CuSparseMatrixCSC(sparse(A))
prob_gpu_sparse2 = LinearProblem(A_gpu_sparse2, b_gpu)
solve(prob_gpu_sparse2) # fails because of generic LU


# symmetric matrix on GPU (dense)
A_gpu_sym = adapt(CuArray, A_sym)
prob_gpu_sym = LinearProblem(A_gpu_sym, b_gpu)
solve(prob_gpu_sym) # works

# symetric sparse on GPU
A_gpu_sym_sparse1 = CUDA.CUSPARSE.CuSparseMatrixCSR(sparse(A_sym))
prob_gpu_sym_sparse1 = LinearProblem(A_gpu_sym_sparse1, b_gpu)
solve(prob_gpu_sym_sparse1) # errors in colesky

A_gpu_sym_sparse2 = CUDA.CUSPARSE.CuSparseMatrixCSC(sparse(A_sym))
prob_gpu_sym_sparse2 = LinearProblem(A_gpu_sym_sparse2, b_gpu)
solve(prob_gpu_sym_sparse2) # errors in generic LU
```

### PR DESCRIPTION
**Pull request by hexaeder**
This PR attempts to fix #827 . It requires a revert of #828 (PRed in #833)

This fixes mainly cache creaction problems. Now, based on whether CUDSS is loaded and whether a CSC or CSR matrix is provided it skips the cholesky and/or lu cache build.

Also changes the default solver logic:
- `CuSparseMatrixCSR` -> Krylov if CUDSS not loaded (warns once), LU otherwise
- `CuSparseMatrixCSR` -> Krylov (warns once about this)

It also adds some tests for the default solver choice before and after `using CUDSS` and fixes some missing import in the cuda tests.

## Checklist

- [X] Appropriate tests were added
- [X] Any code changes were done in a way that does not break public API
- [X] All documentation related to code changes were updated
- [-] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC). (new code does, surruding code does not)
- [X] Any new documentation only uses public API

### CODE REVIEW

File: ext/LinearSolveSparseArraysExt.jl [hunk 1]
```diff
@@ -344,7 +344,13 @@ function LinearSolve.init_cacheval(alg::NormalCholeskyFactorization,
             Symmetric{T, <:AbstractSparseArray{T}}}, b, u, Pl, Pr,
         maxiters::Int, abstol, reltol, verbose::Union{LinearVerbosity, Bool},
         assumptions::OperatorAssumptions) where {T <: BLASELTYPES}
-    ArrayInterface.cholesky_instance(convert(AbstractMatrix, A))
+    if LinearSolve.is_cusparse_csc(A)
+        nothing
+    elseif LinearSolve.is_cusparse_csr(A) && !LinearSolve.cudss_loaded(A)
+        nothing
```
Comment (ChrisRackauckas) [inline ext/LinearSolveSparseArraysExt.jl:350]: Would it instead make sense to just fix cholesky instance for GPUs?

Comment (hexaeder) [reply ext/LinearSolveSparseArraysExt.jl:350]: We could have a extension (either in ArrayInterface or CUDSS) to define
```julia
ArrayInterface.cholesky_instance(::CuSparseCSR)
```
the Problem is that if CUDSS is not loaded, the extension would not trigger, the specialization would not load and ArrayInterface would still fallback to `LinearAlgebra.cholesky` for `A::Any` which errors out.

Or do you mean something else?
