### PR TITLE
Fix KLU reuse path for AbstractSparseMatrixCSC and avoid shared preallocated cache state

### LINKED ISSUE #737: KLUFactorization fails with AbstractSparseMatrixCSC
**Describe the bug 🐞**

If given an AbstractSparseMatrixCSC, solving a linear problem with KLUFactorization()
errors, while it works with UMFPACK, Sparspak and Pardiso.

**Expected behavior**
Creating a linear problem with a subtype of AbstractSparseMatrixCSC and solving
it whith KLU should work similar to  UMFPACK, Sparspak and Pardiso.

**Minimal Reproducible Example 👇**
```julia
using LinearAlgebra, SparseArrays, LinearSolve
using Pardiso
using Sparspak


struct MySparseMatrixCSC{Tv, Ti} <: SparseArrays.AbstractSparseMatrixCSC{Tv, Ti}
    csc::SparseMatrixCSC{Tv, Ti}
end

Base.size(m::MySparseMatrixCSC) = size(m.csc)
SparseArrays.getcolptr(m::MySparseMatrixCSC) = SparseArrays.getcolptr(m.csc)
SparseArrays.rowvals(m::MySparseMatrixCSC) = SparseArrays.rowvals(m.csc)
SparseArrays.nonzeros(m::MySparseMatrixCSC) = SparseArrays.nonzeros(m.csc)

function main(; N = 10000, solver = UMFPACKFactorization())
    A = spdiagm(1 => -ones(N - 1), 0 => fill(10.0, N), -1 => -ones(N - 1))
    u0 = ones(size(A, 2))
    b = A * u0
    MyA = MySparseMatrixCSC(A)

    prob = LinearProblem(MyA, b)
    u = LinearSolve.solve(prob, solver)

    @show n = norm(u - u0, Inf)
    if n < 1.0e-12
        println("$(typeof(solver)) ok")
    else
        println("$(typeof(solver)): wrong solution")
    end
    return nothing
end


main()
main(solver = MKLPardisoFactorize())
main(solver = SparspakFactorization())
main(solver = KLUFactorization())
```

**Error & Stacktrace ⚠️**

```julia
n = norm(u - u0, Inf) = 2.220446049250313e-16
UMFPACKFactorization ok
n = norm(u - u0, Inf) = 0.0
PardisoJL{Int64, Nothing} ok
n = norm(u - u0, Inf) = 1.1102230246251565e-16
SparspakFactorization ok
ERROR: LoadError: DimensionMismatch:
Stacktrace:
[1] klu!(K::LinearSolveSparseArraysExt.KLU.KLUFactorization{Float64, Int64}, nzval::Vector{Float64}; check::Bool, allowsingular::Bool)
@ LinearSolveSparseArraysExt.KLU ~/Wias/work/julia/dev/LinearSolve/src/KLU/klu.jl:652
[2] klu!
@ ~/Wias/work/julia/dev/LinearSolve/src/KLU/klu.jl:650 [inlined]
[3] solve!(cache::LinearSolve.LinearCache{MySparseMatrixCSC{Float64, Int64}, Vector{Float64}, Vector{Float64}, SciMLBase.NullParameters, KLUFactorization, LinearSolveSparseArraysExt.KLU.KLUFactorization{Float64, Int64}, IdentityOperator, IdentityOperator, Float64, Bool, LinearSolveAdjoint{Missing}}, alg::KLUFactorization; kwargs::@Kwargs{})
@ LinearSolveSparseArraysExt ~/Wias/work/julia/dev/LinearSolve/ext/LinearSolveSparseArraysExt.jl:263
[4] solve!
@ ~/Wias/work/julia/dev/LinearSolve/ext/LinearSolveSparseArraysExt.jl:251 [inlined]
[5] #solve!#12
@ ~/Wias/work/julia/dev/LinearSolve/src/common.jl:424 [inlined]
[6] solve!
@ ~/Wias/work/julia/dev/LinearSolve/src/common.jl:423 [inlined]
[7] #solve#11
@ ~/Wias/work/julia/dev/LinearSolve/src/common.jl:420 [inlined]
[8] solve
@ ~/Wias/work/julia/dev/LinearSolve/src/common.jl:418 [inlined]
[9] main(; N::Int64, solver::KLUFactorization)
@ Main ~/Wias/work/julia/dev/LinearSolve/quarry/kluproblem.jl:26
[10] top-level scope
@ ~/Wias/work/julia/dev/LinearSolve/quarry/kluproblem.jl:41
[11] include(mod::Module, _path::String)
@ Base ./Base.jl:303
[12] exec_options(opts::Base.JLOptions)
@ Base ./client.jl:321
[13] _start()
@ Base ./client.jl:554
in expression starting at /home/fuhrmann/Wias/work/julia/dev/LinearSolve/quarry/kluproblem.jl:41
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
[2169fc97] AlgebraicMultigrid v1.1.0
[0a1fb500] BlockDiagonals v0.2.0
[95c220a8] ExtendableSparse v1.7.1
[f6369f11] ForwardDiff v1.0.1
[88f59080] ILUZero v0.2.0
[40713840] IncompleteLU v0.2.1
[42fd0dbc] IterativeSolvers v0.9.4
[0b1a1467] KrylovKit v0.10.0
[45d422c2] KrylovPreconditioners v0.3.6
[7ed4a6bd] LinearSolve v3.27.0 `~/Wias/work/julia/dev/LinearSolve`
[bdf0d083] MultiFloats v2.3.0
[46dd5b70] Pardiso v1.0.1
[c0aeaf25] SciMLOperators v1.5.0
[e56a9233] Sparspak v0.3.12
[856f044c] MKL_jll v2025.2.0+0
[37e2e46d] LinearAlgebra v1.12.0
[2f01184e] SparseArrays v1.12.0
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
⌃ [47edcb42] ADTypes v1.16.0
[7d9f7c33] Accessors v0.1.42
[79e6a3ab] Adapt v4.3.0
[2169fc97] AlgebraicMultigrid v1.1.0
[ec485272] ArnoldiMethod v0.4.0
[4fba245c] ArrayInterface v7.19.0
[4c555306] ArrayLayouts v1.11.2
[a9b6321e] Atomix v1.1.2
[0a1fb500] BlockDiagonals v0.2.0
[fa961155] CEnum v0.5.0
[d360d2e6] ChainRulesCore v1.26.0
[38540f10] CommonSolve v0.2.4
[bbf7d656] CommonSubexpressions v0.3.1
[34da2185] Compat v4.18.0
[a33af91c] CompositionsBase v0.1.2
[2569d6c7] ConcreteStructs v0.2.3
[187b0558] ConstructionBase v1.6.0
[a8cc5b0e] Crayons v4.1.1
[9a962f9c] DataAPI v1.16.0
⌅ [864edb3b] DataStructures v0.18.22
[e2d170a0] DataValueInterfaces v1.0.0
[163ba53b] DiffResults v1.1.0
[b552c78f] DiffRules v1.15.1
[ffbed154] DocStringExtensions v0.9.5
[4e289a0a] EnumX v1.0.5
[e2ba6199] ExprTools v0.1.10
[55351af7] ExproniconLite v0.10.14
[95c220a8] ExtendableSparse v1.7.1
[1a297f60] FillArrays v1.13.0
[f6369f11] ForwardDiff v1.0.1
[069b7b12] FunctionWrappers v1.1.3
[77dc65aa] FunctionWrappersWrappers v0.1.3
[46192b85] GPUArraysCore v0.2.0
[86223c79] Graphs v1.13.0
[88f59080] ILUZero v0.2.0
[40713840] IncompleteLU v0.2.1
[d25df0c9] Inflate v0.1.5
[3587e190] InverseFunctions v0.1.17
[92d709cd] IrrationalConstants v0.2.4
[42fd0dbc] IterativeSolvers v0.9.4
[82899510] IteratorInterfaceExtensions v1.0.0
[692b3bcd] JLLWrappers v1.7.1
[ae98c720] Jieko v0.2.1
[63c18a36] KernelAbstractions v0.9.38
[ba0b0d4f] Krylov v0.10.1
[0b1a1467] KrylovKit v0.10.0
[45d422c2] KrylovPreconditioners v0.3.6
[b964fa9f] LaTeXStrings v1.4.0
[5078a376] LazyArrays v2.6.2
[7ed4a6bd] LinearSolve v3.27.0 `~/Wias/work/julia/dev/LinearSolve`
[2ab3a3ac] LogExpFunctions v0.3.29
[1914dd2f] MacroTools v0.5.16
[2679e427] Metis v1.5.0
[2e0e35c7] Moshi v0.3.7
[bdf0d083] MultiFloats v2.3.0
[77ba4419] NaNMath v1.1.3
[6fe1bfb0] OffsetArrays v1.17.0
[bac558e1] OrderedCollections v1.8.1
[65ce6f38] PackageExtensionCompat v1.0.2
[46dd5b70] Pardiso v1.0.1
[aea7be01] PrecompileTools v1.3.2
[21216c6a] Preferences v1.5.0
[08abe8d2] PrettyTables v2.4.0
[3cdcf5f2] RecipesBase v1.3.4
⌃ [731186ca] RecursiveArrayTools v3.37.0
[189a3867] Reexport v1.2.2
[ae029012] Requires v1.3.1
[7e49a35a] RuntimeGeneratedFunctions v0.5.15
[fdea26ae] SIMD v3.7.1
⌃ [0bca4576] SciMLBase v2.108.0
[c0aeaf25] SciMLOperators v1.5.0
[53ae85a6] SciMLStructures v1.7.0
[efcf1570] Setfield v1.1.2
[699a6c99] SimpleTraits v0.9.5
[e56a9233] Sparspak v0.3.12
[276daf66] SpecialFunctions v2.5.1
[90137ffa] StaticArrays v1.9.14
[1e83bf80] StaticArraysCore v1.4.3
[10745b16] Statistics v1.11.1
[892a3eda] StringManipulation v0.4.1
⌃ [2efcf032] SymbolicIndexingInterface v0.3.42
[3783bdb8] TableTraits v1.0.1
[bd369af6] Tables v1.12.1
[3a884ed6] UnPack v1.0.2
[013be700] UnsafeAtomics v0.3.0
[409d34a3] VectorInterface v0.5.0
[1d5cc7b8] IntelOpenMP_jll v2025.2.0+0
[d00139f3] METIS_jll v5.1.3+0
[856f044c] MKL_jll v2025.2.0+0
[efe28fd5] OpenSpecFun_jll v0.5.6+0
[1317d2d5] oneTBB_jll v2022.0.0+0
[0dad84c5] ArgTools v1.1.2
[56f22d72] Artifacts v1.11.0
[2a0f44e3] Base64 v1.11.0
[ade2ca70] Dates v1.11.0
[8ba89e20] Distributed v1.11.0
[f43a241f] Downloads v1.6.0
[7b1f6079] FileWatching v1.11.0
[9fa8497b] Future v1.11.0
[b77e0a4c] InteractiveUtils v1.11.0
[ac6e5ff7] JuliaSyntaxHighlighting v1.12.0
[4af54fe1] LazyArtifacts v1.11.0
[b27032c2] LibCURL v0.6.4
[76f85450] LibGit2 v1.11.0
[8f399da3] Libdl v1.11.0
[37e2e46d] LinearAlgebra v1.12.0
[56ddb016] Logging v1.11.0
[d6f4376e] Markdown v1.11.0
[a63ad114] Mmap v1.11.0
[ca575930] NetworkOptions v1.3.0
[44cfe95a] Pkg v1.13.0
[de0858da] Printf v1.11.0
[9a3f8284] Random v1.11.0
[ea8e919c] SHA v0.7.0
[9e88b42a] Serialization v1.11.0
[1a1011a3] SharedArrays v1.11.0
[6462fe0b] Sockets v1.11.0
[2f01184e] SparseArrays v1.12.0
[f489334b] StyledStrings v1.11.0
[4607b0f0] SuiteSparse
[fa267f1f] TOML v1.0.3
[a4e569a6] Tar v1.10.0
[8dfed614] Test v1.11.0
[cf7118a7] UUIDs v1.11.0
[4ec0a83e] Unicode v1.11.0
[e66e0078] CompilerSupportLibraries_jll v1.3.0+1
[deac9b47] LibCURL_jll v8.11.1+1
[e37daf67] LibGit2_jll v1.9.0+0
[29816b5a] LibSSH2_jll v1.11.3+1
[14a3606d] MozillaCACerts_jll v2025.5.20
[4536629a] OpenBLAS_jll v0.3.29+0
[05823500] OpenLibm_jll v0.8.5+0
[458c3c95] OpenSSL_jll v3.5.1+0
[bea87d4a] SuiteSparse_jll v7.8.3+2
[83775a58] Zlib_jll v1.3.1+2
[8e850b90] libblastrampoline_jll v5.13.1+0
[8e850ede] nghttp2_jll v1.64.0+1
[3f19e933] p7zip_jll v17.5.0+2
```

  - Output of `versioninfo()`

```julia
Julia Version 1.12.0-rc1
Commit 228edd6610b (2025-07-12 20:11 UTC)
Build Info:
Official https://julialang.org release
Platform Info:
OS: Linux (x86_64-linux-gnu)
CPU: 20 × 13th Gen Intel(R) Core(TM) i7-13700H
WORD_SIZE: 64
LLVM: libLLVM-18.1.7 (ORCJIT, alderlake)
GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 20 virtual cores)
Environment:
JULIA_PROJECT = @LinearSolve
LD_LIBRARY_PATH = /home/fuhrmann/local/lib64:/home/fuhrmann/local/lib:.:/usr/local/lib64:/usr/local/lib:/home/fuhrmann/local/lib:/home/fuhrmann/Sys/share/pardiso
JULIA_PKG_DEVDIR = /home/fuhrmann/Wias/work/julia/dev
JULIA_MAX_NUM_PRECOMPILE_FILES = 50
JULIA_PKG_SERVER_REGISTRY_PREFERENCE = eager
JULIA_PARDISO = /home/fuhrmann/Sys/share/pardiso/panua-pardiso-20240229-linux/lib
JULIA_HISTORY = /home/fuhrmann/.julia_histories/_home_fuhrmann_Wias_work_julia_dev_LinearSolve
```

**Additional context**

### PR DESCRIPTION
**Pull request by AJ0070**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API
  
## Additional context

This PR fixes KLUFactorization behavior with AbstractSparseMatrixCSC wrappers.

### What changed
In `LinearSolveSparseArraysExt.jl`:
- Generalized `pattern_changed` dispatch from concrete `SparseMatrixCSC` to `AbstractSparseMatrixCSC`.
- Switched row index access in pattern checks to `SparseArrays.rowvals(A)` (interface-based).
- Replaced shared `PREALLOCATED_KLU` use for `Float64`/`Int64` cache init with a fresh `KLU.KLUFactorization(...)` instance per cache init.

### Why
- KLU symbolic reuse/pattern checks should work for sparse wrapper types implementing the CSC interface.
- Shared mutable KLU preallocation can leak state across caches/solves; returning a fresh factorization avoids this.

fix #737 

AI Disclosure: used codex

### CODE REVIEW

File: ext/LinearSolveSparseArraysExt.jl [hunk 1]
```diff
@@ -308,20 +308,17 @@ function LinearSolve.init_cacheval(
...
         maxiters::Int, abstol,
         reltol,
         verbose::Union{LinearVerbosity, Bool}, assumptions::OperatorAssumptions
     )
-    return PREALLOCATED_KLU
+    return KLU.KLUFactorization(
+        SparseMatrixCSC{Float64, Int64}(
+            0, 0, [Int64(1)], Int64[], Float64[]
+        )
+    )
```
Comment (ChrisRackauckas) [inline ext/LinearSolveSparseArraysExt.jl]: why was this removed?

Comment (AJ0070) [reply ext/LinearSolveSparseArraysExt.jl]: `PREALLOCATED_KLU` was a shared mutable singleton. Since `KLU` mutates its factorization during solves, caches could end up reusing stale state and cause `DimensionMismatch` errors. Creating a fresh `KLU.KLUFactorization` in each `init_cacheval` keeps cache state isolated and fixes the issue.

Comment (ChrisRackauckas) [reply ext/LinearSolveSparseArraysExt.jl]: But it will allocate when it changes the size? So it shouldn't cause an issue. What this allows is for it to not allocate when it's not chosen by the default method, like matrix-free cases and such.

Comment (AJ0070) [reply ext/LinearSolveSparseArraysExt.jl]: okay, got it. reverting it.

**Comment by AJ0070** [comment]
@ChrisRackauckas tests are passing!

**Comment by AJ0070** [comment]
trim tests are flaky and tricky to fix! I am looking for a solution
